# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-09 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchCourse', '0002_auto_20160609_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedata',
            old_name='course_url',
            new_name='course_homepage_url',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_video_url',
            field=models.URLField(null=True),
        ),
    ]
